### ISSUE TITLE
group bt date_part or extract  fails

### ISSUE THREAD

**Issue by alanrigele** [adjust/clickhouse_fdw#11]
Hi. 

First of all, thank you for the work you are doing. The FDW we have been using has be far more stable and better performance than before.

We have seen a fault with the date_part (extract) function in the the group by  push down to clickhouse.

A request like this will work  fine
select extract('year' from "startDateTime") 
             from ran.kpi_cell_data 
               where "startDateTime"::date >= '2019/09/28'::date
                            and "startDateTime"::date <= '2019/09/30'::date 
                            and site = '0001'

But the following will fail with the response (\ERROR: clickhouse_fdw: DB::Exception: Unknown function date_part)

select date_part('day',"startDateTime") 
     from ran.kpi_cell_data 
      where "startDateTime"::date >= '2019/09/28'::date 
          and "startDateTime"::date <= '2019/09/30'::date 
          and site = '0001'
      group by date_part('day',"startDateTime")

select extract('year' from "startDateTime") 
       from ran.kpi_cell_data 
          where "startDateTime"::date >= '2019/09/28'::date 
              and "startDateTime"::date <= '2019/09/30'::date 
              and site = '0001'
          group by extract('year' from "startDateTime")

We have tried multiple options and settings but it seems like an issue in the mapping of the functions

**Comment by ildus** [comment]
Yes, we don't support `date_part` yet, I will look into it.

**Comment by ildus** [comment]
Pushed in last commit, there is some problem with docker build, but all good in my local build.
