### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by chenyineng1024** [adjust/clickhouse_fdw#12]
Hi, Ildus,

I want to try your FDW, but I got the following ERROR when I 'make' the master branch. Anything wrong?

[ 87%] Built target clickhouse_fdw_sql
make[1]: *** No rule to make target 'src/CMakeFiles/install.dir/all', needed by 'src/CMakeFiles/clickhouse_fdw.dir/all'.  Stop.
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Yineng

**Comment by ildus** [comment]
Hi, I would need more information. Please send here all output from:
```
mkdir build && cd build
cmake ..
make VERBOSE=1
```

**Comment by chenyineng1024** [comment]
I think something wrong with line 449 of clickhouse_fdw/build/CMakeFiles/Makefile2

src/CMakeFiles/clickhouse_fdw.dir/all: src/CMakeFiles/install.dir/all

I modify it with following

src/CMakeFiles/clickhouse_fdw.dir/all: libclickhouse/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/all

but still has something wrong

[ 87%] Built target clickhouse_fdw_sql
make -f src/CMakeFiles/clickhouse_fdw.dir/build.make src/CMakeFiles/clickhouse_fdw.dir/depend
make[2]: Entering directory '/home/cyn/usr/clickhouse_fdw/build'
cd /home/cyn/usr/clickhouse_fdw/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/cyn/usr/clickhouse_fdw /home/cyn/usr/clickhouse_fdw/src /home/cyn/usr/clickhouse_fdw/build /home/cyn/usr/clickhouse_fdw/build/src /home/cyn/usr/clickhouse_fdw/build/src/CMakeFiles/clickhouse_fdw.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/cyn/usr/clickhouse_fdw/build'
make -f src/CMakeFiles/clickhouse_fdw.dir/build.make src/CMakeFiles/clickhouse_fdw.dir/build
make[2]: Entering directory '/home/cyn/usr/clickhouse_fdw/build'
[ 88%] Building C object src/CMakeFiles/clickhouse_fdw.dir/clickhousedb_connection.c.o
cd /home/cyn/usr/clickhouse_fdw/build/src && /usr/bin/cc -Dclickhouse_fdw_EXPORTS -I/home/cyn/usr/clickhouse_fdw/src/PRIVATE -I"/home/cyn/usr/clickhouse_fdw/src/You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application." -I/home/cyn/usr/clickhouse_fdw/libclickhouse/include  -fPIC   You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev client-side application. -fstack-protector -fstack-check -o CMakeFiles/clickhouse_fdw.dir/clickhousedb_connection.c.o   -c /home/cyn/usr/clickhouse_fdw/src/clickhousedb_connection.c
cc: error: You: No such file or directory
cc: error: need: No such file or directory
cc: error: to: No such file or directory
cc: error: install: No such file or directory
cc: error: postgresql-server-dev-NN: No such file or directory
cc: error: for: No such file or directory
cc: error: building: No such file or directory
cc: error: a: No such file or directory
cc: error: server-side: No such file or directory
cc: error: extension: No such file or directory
cc: error: or: No such file or directory
cc: error: libpq-dev: No such file or directory
cc: error: client-side: No such file or directory
cc: error: application.: No such file or directory
src/CMakeFiles/clickhouse_fdw.dir/build.make:62: recipe for target 'src/CMakeFiles/clickhouse_fdw.dir/clickhousedb_connection.c.o' failed
make[2]: *** [src/CMakeFiles/clickhouse_fdw.dir/clickhousedb_connection.c.o] Error 1
make[2]: Leaving directory '/home/cyn/usr/clickhouse_fdw/build'
CMakeFiles/Makefile2:450: recipe for target 'src/CMakeFiles/clickhouse_fdw.dir/all' failed
make[1]: *** [src/CMakeFiles/clickhouse_fdw.dir/all] Error 2
make[1]: Leaving directory '/home/cyn/usr/clickhouse_fdw/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chenyineng1024** [comment]
I have succeed built the project, with some adjustment on installed packages. I will try again on a fresh environment later to see what's the root problem.

**Comment by chenyineng1024** [comment]
By the way, I have another question, why it needs PG version 11 or 12?

**Comment by chenyineng1024** [comment]
I tried PG 9.4.23 but I found some referenced code was different between PG 9.4.23 and PG 11.

**Comment by chenyineng1024** [comment]
I tried PG 9.4.23 but I found some referenced code was different between PG 9.4.23 and PG 11.

**Comment by ildus** [comment]
pg10 introduced aggregated push downs, and so it's not possible to make proper FDW. I have not tried to compile `clickhouse_fdw` with pg10 though.
