### ISSUE TITLE
Tables containing VARCHAR type are not imported

### ISSUE THREAD

**Issue by ipnix** [adjust/clickhouse_fdw#13]
Thanks so much for FDW. Already started to use between our bases.
When using the `IMPORT FOREIGN SCHEMA "emma" FROM SERVER ch_servertv INTO ch_db;` command, we found the following error:
```

ERROR:  syntax error at or near ","
LINE 5:  "block_type" VARCHAR(50)),                                       

QUERY:  CREATE FOREIGN TABLE ch_db.merged_blocks (
	"block_begin_time" INT4,
	"block_date" DATE NOT NULL,
	"block_is_actual" INT2,
	"block_type" VARCHAR(50)),
	"block_volume" INT2
) SERVER ch_servertv OPTIONS (table_name 'merged_blocks');
```
The text of the command uses a double character to create an external table `))`.

**Comment by ildus** [comment]
Thanks for discovering the bug, will fix it today

**Comment by ildus** [comment]
Could you send me your clickhouse table definition?

**Comment by ipnix** [comment]
CREATE TABLE merged_blocks
(
    `block_begin_time` Nullable(Int32), 
    `block_date` Date, 
    `block_vimb_is_actual` Nullable(UInt8), 
    `block_type` Nullable(FixedString(50)), 
    `block_volume` Nullable(Int8)     
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(block_date)
PRIMARY KEY (block_id, block_date)
ORDER BY (block_id, block_date)
SETTINGS index_granularity = 8192

**Comment by ipnix** [comment]
Table definition:
```
CREATE TABLE merged_blocks
(
    block_begin_time Nullable(Int32), 
    block_date Date, 
    block_is_actual Nullable(UInt8), 
    block_type Nullable(FixedString(50)), 
    block_volume Nullable(Int8)     
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(block_date)
PRIMARY KEY (block_date)
ORDER BY (block_date)
SETTINGS index_granularity = 8192
```

**Comment by ildus** [comment]
Fix for IMPORT SCHEMA is pushed, but found another error with SELECT queries on FixedString columns.

**Comment by ildus** [comment]
Fixed
