### ISSUE TITLE
INSERT operations to a Clickhouse table with  field type of Nullable are not performed

### ISSUE THREAD

**Issue by ipnix** [adjust/clickhouse_fdw#15]
In DB PostgreSQL created a table in the database and filled it with data. Some fields were filled with NULL values:
```
CREATE TABLE test.merged_blocks_test_null (
  block_begin_time INTEGER,
  block_date DATE NOT NULL,
  block_is_actual SMALLINT,
  block_volume SMALLINT
) 

INSERT INTO test.merged_blocks_test_null ("block_begin_time", "block_date", "block_is_actual", "block_volume")
VALUES 
  (1, E'2019-10-10', NULL, NULL),
  (2, E'2019-10-10', NULL, NULL),
  (3, E'2019-10-12', 1, 1);
```
Clickhouse created a table in the database:
```
CREATE TABLE merged_blocks_test_nullable
(
    block_begin_time Nullable(Int32), 
    block_date Date, 
    block_is_actual Nullable(UInt8), 
    block_volume Nullable(Int8)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(block_date)
PRIMARY KEY block_date
ORDER BY block_date
SETTINGS index_granularity = 8192
```
In the database, PostgreSQL created external table **ch_db_http.merged_blocks_test_nullable** using the command:
`IMPORT FOREIGN SCHEMA "emma" FROM SERVER ch_emma_http INTO ch_db_http;`

Then, when performing an `INSERT INTO SELECT` operation, an error occurs:
```
INSERT INTO ch_db_http.merged_blocks_test_nullable
SELECT * FROM test.merged_blocks_test_null
```

Presumably in the code section::
https://github.com/adjust/clickhouse_fdw/blob/b9ff511076a647fc92b3cab3a5efd51439bec860/src/clickhousedb_fdw.c#L1559-L1563

we made a temporary fix:

```
if (isnull)
{
	appendStringInfoString(&fmstate->sql, "\\N");
	continue;
}
```
This helped us import a table containing type fields **Nullable**.
Perhaps we did not take into account all the details when fixing, is it possible to check this error?
Thanks!

**Comment by ildus** [comment]
It is the same problem as in your another issue.

**Comment by ildus** [comment]
IMPORT FOREIGN SCHEMA is not related with inserting data. Can you show what clickhouse error on inserting?

**Comment by ildus** [comment]
Ok, I have pushed your fix. Thanks for the reporting

**Comment by ipnix** [comment]
> IMPORT FOREIGN SCHEMA is not related with inserting data. Can you show clickhouse error on inserting?

```
ERROR:  clickhouse_fdw:Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected \t before: NULL\tNULL\n2\t2019-10-10\tNULL\tNULL\n3\t2019-10-12\t1\t1\n: (at row 1)

Row 1:
Column 0,   name: block_begin_time, type: Nullable(Int32), parsed text: "1"
Column 1,   name: block_date,       type: Date,            parsed text: "2019-10-10"
Column 2,   name: block_is_actual,  type: Nullable(UInt8), parsed text: <EMPTY>
ERROR: garbage after Nullable(UInt8): "NULL<TAB>NULL<LINE FEED>"


QUERY:INSERT INTO "emmaTv".merged_blocks_test_nullable(block_begin_time, block_date, block_is_actual, block_volume) FORMAT TSV
1	2019-10-10	NULL	NULL
2	2019-10-10	NULL	NULL
3	2019-10-12	1	1
```

**Comment by ipnix** [comment]
> Ok, I have pushed your fix. Thanks for the reporting

Thanks!

**Comment by ildus** [comment]
All good now?

**Comment by ipnix** [comment]
I downloaded new changes from the master branch. Checked, now is OK!
**Thank you very much!:)**
