### ISSUE TITLE
INSERT INTO SELECT operation on large tables

### ISSUE THREAD

**Issue by ipnix** [adjust/clickhouse_fdw#17]
In PostgreSQL there is a _table data_marts.merged_blocks_ whose size is **8Gb**
Attempting to perform the _INSERT INTO SELECT_ operation produces the following error (SELECT from table PG. INSERT INTO at Clickhouse):
```
ERROR:  out of memory
DETAIL:  Cannot enlarge string buffer containing 1073741810 bytes by 32 more bytes.
CONTEXT:  SQL statement "INSERT INTO ch_db_http.merged_blocks
SELECT
```
The error occurs on  side of the PostgreSQL.

Table _data_marts.merged_blocks_  has 12 million rows. When using the operator LIMIT 1 000 000, it will turn out to fulfill the request.

**Comment by ildus** [comment]
That doesn't look as good idea. The data will be copied to postgres and back.

**Comment by ipnix** [comment]
In PostgreSQL, we store all the data that services collect. At Clickhouse, we do analytics. And with INSERT INTO SELECT queries, we want to create data marts in Clickhouse based on PostgreSQL data. And the FDW INSERT INTO SELECT method looks like a very convenient solution. Indeed, in PostgreSQL it is convenient to perform SELECT JOIN operations - which allows you to create denormalized tables and at the same time through INSERT to copy data to the Clickhouse.

**Comment by ildus** [comment]
Removed my comment after re-reading the initial text. I will look into this tomorrow.

**Comment by ipnix** [comment]
Do you plan to support large tables in the future?

**Comment by ildus** [comment]
This issue was closed with fixing commit. Now large tables are supported.

**Comment by ipnix** [comment]
> This issue was closed with fixing commit. Now large tables are supported. Could you please test that it is fixed?

I checked it with pleasure. Everything is super! It turns out to fill in large tables. Very grateful for the fix!:)
