### ISSUE TITLE
Version mismatch during CREATE EXTENSION on PG12.0

### ISSUE THREAD

**Issue by edwinkong** [adjust/clickhouse_fdw#18]
Background Information:
PostgreSQL Version: PostgreSQL 12.0
OS: Red Hat Enterprise Linux 7.7

I have a compiled from source in master branch on 24 Oct 2019 and installed into /usr/pgsql-12
Executing `CREATE EXTENSION clickhouse-fdw;` returns

ERROR:  incompatible library "/usr/pgsql-12/lib/clickhouse_fdw.so": version mismatch
DETAIL:  Server is version 12, library is version 11.
SQL state: XX000

**Comment by ildus** [comment]
Could you show `pg_config` output which is used for `clickhouse_fdw` compilation?

**Comment by edwinkong** [comment]
BINDIR = /usr/pgsql-12/bin
DOCDIR = /usr/pgsql-12/doc
HTMLDIR = /usr/pgsql-12/html
INCLUDEDIR = /usr/pgsql-12/include
PKGINCLUDEDIR = /usr/pgsql-12/include
LIBDIR = /usr/pgsql-12/lib
LOCALEDIR = /usr/pgsql-12/share/locale
MANDIR = /usr/pgsql-12/share/man
SHAREDIR = /usr/pgsql-12/share
SYSCONGDIR = /etc/sysconfig/pgsql
PGXS = /usr/pgsql-12/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = ‘—enable-path’ ‘—prefix=/usr/pgsql-12’ ‘—includedir=/usr/pgsql-12/include’ ‘—mandir=/usr/pgsql-12/share/man’ r/pgsql-12/share
CC = gcc -std=gnu99
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxm12 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -W declaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-rmat-security -fno
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,—as-needed -L/usr/lib64/llvm5.0/lib -L/usr/lib64 -Wl,—as-needed -Wl,-rpath,’/usr/pgsql-12/lib’—enable-new-dt
LDFLAGS_EX =
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -l
VERSION = PostgreSQL 12.0

**Comment by ildus** [comment]
Have you tried to recompile after `make clean`?

**Comment by edwinkong** [comment]
Yes but not successful. I even deleted the whole repo but still it compiles to version 11.

**Comment by ildus** [comment]
I think you have somehere pg11 header files.

**Comment by edwinkong** [comment]
Oh I deleted the folder /var/lib/pgsql/11 and refreshed the pgAdmin 4 to execute the `CREATE EXTENSION clickhouse_fdw` and it works for me now! Thank you for your help.
