### ISSUE TITLE
has() translated from IN operator suffers from performance problem for long scalar array

### ISSUE THREAD

**Issue by edwinkong** [adjust/clickhouse_fdw#20]
The clickhouse-fdw translates `SELECT * FROM table WHERE col IN ('a', 'b','c')` to
`SELECT [columns] FROM table WHERE has(['a','b','c'], 'col')`

However the `has()` function seems to do repeated table scans in `clickhouse`, which suffers from performance problem if the list grows long.

The function `static void deparseScalarArrayOpExpr(ScalarArrayOpExpr *node, deparse_expr_cxt *context)` in `clickhousedb-deparse.c` is responsible of wrapping the square bracket scalar array in has() function. I did an ugly patch for that and it worked for my simple case but is there a reason to use the `has()` function and square bracket instead of original `IN` operator?

**Comment by ildus** [comment]
can I see your patch? maybe I can just use it

**Comment by ildus** [comment]
Problem here is that IN in postgres translated to `ANY()` function in the plan (one of cases of `scalar op ANY/ALL`), which are translated to  `has` function. There is no way to know that initially it was `IN`. BTW, clickhouse_fdw support only `=` and `<>` operations for ANY/ALL.

**Comment by ildus** [comment]
The second problem here is that `ClickHouse` seems to expect tuple for `IN` operation.

**Comment by ildus** [comment]
@edwinkong we have added this feature, so at the end your issue is solved :)
