### ISSUE TITLE
Installation clickhouse_fdw

### ISSUE THREAD

**Issue by lexaamn** [adjust/clickhouse_fdw#22]
Hi! Command "cmake .." completed with error: "CMake Error at src/CMakeLists.txt:39 (target_compile_features):   target_compile_features specified unknown feature "c_std_11" for target
  "clickhouse_fdw"". Which C/C++ compilers is better for clickhouse_fdw? ALT Linux, postgresql11, gcc5, gcc5-c++, libcurl, libuuid are installed on server.

**Comment by ildus** [comment]
Could you try to remove that line?

**Comment by lexaamn** [comment]
When I removed this line: "target_compile_features(clickhouse_fdw PRIVATE c_std_11)" at src/CMakeLists.txt:39, command "cmake .." completed without errors but next command "make" completed with great amount of errors: "This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the 
-std=c++11 or -std=gnu++11 compiler options".
Current version gcc is x86_64-alt-linux-gcc (GCC) 5.3.1. I'm reading, GCC 4.8.1 was the first feature-complete implementation of the 2011 C++ standard: https://gcc.gnu.org/projects/cxx-status.html#cxx11. Therefore, I beleive I must have not any problems.
File build/CMakeFiles/CMakeOutput.log contains next lines:
Detecting CXX [-std=c++1] compile features...
/usr/bin/gcc -std=c++11 -o ...
Can you recommend how to force "cmake" correctly execute a line "target_compile_features(clickhouse_fdw PRIVATE c_std_11)"?
I'm not a programmer for Linux unfortunately, I'm afraid I will be to solve a problem too long. I will be to google "cmake target_compile_features c++11" and to learn recommendations.

**Comment by ildus** [comment]
I've some changes, could you try to recompile the extension?

**Comment by lexaamn** [comment]
Yesterday I solve this problem. Version of cmake must be 3.8+ but  file src/CMakeLists.txt check version 3.5 minimum. I install cmake 3.6.3 earlier but this version not support future c_std_11. Yesterday I install cmake 3.16, gcc 7 (minimum 6.3 for c++14) and commands cmake, make, "make install" are completed succesfully.
Whether I install your "some changes" again?

**Comment by ildus** [comment]
Not sure if I have understood your question. The compilation should be fixed in latest commit, but if everything works on your side now, there is no need to do anything.

**Comment by lexaamn** [comment]
I execute command:
create extension clickhouse_fdw
ERROR: load library "/usr/lib64/pgsql/clickhouse_fdw.so" :
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib64/pgsql/clickhouse_fdw.so)
-----
# ls -l /usr/lib64/libstdc++.*
lrwxrwxrwx 1 root root      19 dec  9 11:47 /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.21
-rw-r--r-- 1 root root 1545576 apr 22  2019 /usr/lib64/libstdc++.so.6.0.21
-----
strings /usr/lib64/libstdc++.so.6.0.21 | grep GLIBCXX
GLIBCXX_3.4, GLIBCXX_3.4.1 - GLIBCXX_3.4.21
-----
#apt-get install libstdc++6
not install new version
-----
gcc --version
gcc (GCC) 7.3.1 20180712 (ALT p8 7.3.1-alt8.M80P.1)
its max version in p8
-----
What to do?

**Comment by lexaamn** [comment]
This problem was solved successfully after I change repository and make full upgrade.
