### ISSUE TITLE
Problem with timestamp selecting mapped in PostgreSQL 

### ISSUE THREAD

**Issue by Rushan4eg** [adjust/clickhouse_fdw#24]
Hello there!

Thanks for your great job! We really like it!

We met with issue related to selecting DateTime field in clickhouse

In clickhouse table we have a field `msgtime` that defined as DateTime type of clickhouse DB. Here is the following example of data │ 2019-12-13 22:46:30 │

In PostgreSQL in foreign table we defined `msgtime` field as `time without time zone ` field.

When we do `SELECT msgtime FROM security_logs LIMIT 10;`
we get only time without dates │22:46:30 │
But expected to get │ 2019-12-13 22:46:30 │

Why this can happen? 

Below the information about CK  schema 
`│ CREATE TABLE SEQUENCEDATA.security_logs ( `msgdate` Date, `string1` Nullable(String), `string2` Nullable(String), `string3` Nullable(String), `string4` Nullable(String), `string5` Nullable(String), `string6` Nullable(String), `string7` Nullable(String), `string8` Nullable(String), `string9` Nullable(String), `string10` Nullable(String)) ENGINE = MergeTree(msgdate, (uniqid, pattern_id, device_ip), 8192) │`

Thanks!

**Comment by mkabilov** [comment]
>In PostgreSQL in foreign table we defined msgtime field as `time without time zone` field.
>When we do `SELECT msgtime FROM security_logs LIMIT 10;` we get only time without dates

are you expecting to get date and time from the "**time** without time zone" postgresql field?

**Comment by Rushan4eg** [comment]
> > In PostgreSQL in foreign table we defined msgtime field as `time without time zone` field.
> > When we do `SELECT msgtime FROM security_logs LIMIT 10;` we get only time without dates
> 
> are you expecting to get date and time from the "**time** without time zone" postgresql field?

Oh damn..Thanks for the idea!
I changed column type ti timestamp without timezone with 
` ALTER TABLE security_logs ALTER COLUMN msgtime TYPE timestamp without time zone;`

and everything works great now!
Just noticed that time select little bit slower now

**Comment by ildus** [comment]
If you're using `http` protocol, try `binary`. It could help
