### ISSUE TITLE
DateTime interval

### ISSUE THREAD

**Issue by Rushan4eg** [adjust/clickhouse_fdw#25]
Hi there!

Thanks for your job! 

I tried to query time interval (for the whole day of today) and directly in CH it worked well, but through the ch_fdw it didn't work..

```
SELECT msgtime as X, 
count(msgtime) as Y 
FROM table
WHERE msgtime >= toStartOfDay(today()) AND msgtime < toStartOfDay(today()+1)
GROUP BY msgtime 
ORDER BY msgtime asc 
LIMIT 100;
```
it says that :

```
ERROR:  function today() does not exist
LINE 4: WHERE msgtime >= toStartOfDay(today()) AND msgtime < toStart...
                                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Does the clickhouse_fdw support DateTime intervals?

**Comment by ildus** [comment]
There is no such function as `today`  in PostgreSQL. Only `current_timestamp` and `current_date`.

**Comment by ildus** [comment]
It looks you're just trying to run ClickHouse queries against PostgreSQL. They would not work. You should make Postgres queries, and they can be converted to ClickHouse sometimes (not in all cases).

**Comment by Rushan4eg** [comment]
Thanks for help!

It worked with that query

```
SELECT msgtime as X,
count(msgtime) as Y
FROM table
WHERE msgtime > CURRENT_DATE - interval '1 DAY'
GROUP BY msgtime
ORDER BY msgtime asc;
```
