### ISSUE TITLE
Docker with clickhouse_fdw

### ISSUE THREAD

**Issue by nnnet** [adjust/clickhouse_fdw#29]
Could you create a docker file with build clickhouse_fdw
Tnx

**Comment by ivmaks** [comment]
https://github.com/implustech/clickhouse_fdw_docker
https://hub.docker.com/r/implustechnology/postgres_clickhouse_fdw

**Comment by nnnet** [comment]
> https://github.com/implustech/clickhouse_fdw_docker
> https://hub.docker.com/r/implustechnology/postgres_clickhouse_fdw

Thank U !
