### ISSUE TITLE
Error on insert text that contains chr(10)

### ISSUE THREAD

**Issue by AppKiv** [adjust/clickhouse_fdw#30]
/* clickhouse */
CREATE TABLE table_test_text
(
    calendar Date, 
    textfield Nullable(String)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(calendar)
ORDER BY (calendar)
SETTINGS index_granularity = 8192

/* postgres */
create schema click;
IMPORT FOREIGN SCHEMA "testdb" LIMIT TO ("table_test_text") FROM SERVER clickhouse_svr INTO click;
/* check select*/
select * from click.table_test_text

/* insert data*/
insert into click.table_test_text(calendar, textfield)
select now()::date, 'test'||chr(10)||'test';

Get Error: 

```
SQL Error [2F000]: ERROR: clickhouse_fdw:Code: 38, e.displayText() = DB::Exception: Cannot parse date: value is too short: (at row 2)

Row 1:
Column 0,   name: calendar,  type: Date,             parsed text: "2020-03-12"
Column 1,   name: textfield, type: Nullable(String), parsed text: "test"

Row 2:
Column 0,   name: calendar,  type: Date,             ERROR: text "test<LINE FEED>" is not like Date


  Detail: query: INSERT INTO testdb.table_test_text(calendar, textfield) FORMAT TSV
2020-03-12	test
test
```
Is it possible to replace or escape char (LF)  inside FDW converter?

**Comment by ildus** [comment]
Thank you for the report, that is a bug, will fix it in few days.

**Comment by ildus** [comment]
@AppKiv should be fixed now, could you please confirm?

**Comment by AppKiv** [comment]
Thanks!
I've checked, bug fixed.
