### ISSUE TITLE
expected comma in AggregateFunction

### ISSUE THREAD

**Issue by rsurgiewicz** [adjust/clickhouse_fdw#31]
Hello
I'm using clickhouse_fdw with Postgres-12.0

Trying to connect it to clickhouse but everytime I'm getting the following error
`ERROR: clickhouse_fdw: expected comma in AggregateFunction`
No matter which FOREIGN SCHEMA I try to import...

Steps I did:
```
CREATE SERVER clickhouse_svr FOREIGN DATA WRAPPER clickhouse_fdw OPTIONS(dbname 'xxxx'',host 'rfb_clickhouse');

CREATE USER MAPPING FOR CURRENT_USER SERVER clickhouse_svr OPTIONS (user 'xxx', password 'xxx');

IMPORT FOREIGN SCHEMA "tax_bills" FROM SERVER clickhouse_svr INTO public;
```

Schema tax_bills comes just from Readme.md:
```
CREATE TABLE tax_bills
(
    bbl Int64,
    owner_name String
)
ENGINE = MergeTree
PARTITION BY bbl
ORDER BY bbl;```


How to nail the issue?

**Comment by ildus** [comment]
I can't reproduce this error.

**Comment by massyah** [comment]
Hi, 
Think I identified what's causing the issue : 
I have a AggregatingMergeTree Materiailized view in my clickhouse schema, and clickhouse_fdw refuses to import it, giving the 
```
ERROR: clickhouse_fdw: expected comma in AggregateFunction
```
error. Dropping the table in CH (just for testing) did "resolve" this issue. 

Any chance the FDW could support 
1) AggregatingMergeTree 
2) Or Postgreqsql syntax to restrict import schema to a set of table ? `IMPORT FOREIGN SCHEMA remote_schema
    [ { LIMIT TO | EXCEPT } ( table_name [, ...] ) ]`
