### ISSUE TITLE
Could not map type when importing foreign schema

### ISSUE THREAD

**Issue by ctlaltdefeat** [adjust/clickhouse_fdw#34]
Using 
```ClickHouse server version 20.4.2.9 (official build).```
```gcc (GCC) 10.1.0```
```psql (PostgreSQL) 12.2```

When running:
```IMPORT FOREIGN SCHEMA "kk" FROM SERVER clickhouse_svr INTO public;```

I run into the following error:
```[XX000] ERROR: clickhouse_fdw: could not map type <6> on events Detail: select name, type from system.columns where database='default' and table='events'```

The clickhouse table ```events``` has the following definition:

```
CREATE TABLE events
(
    id                  String,
    timestamp           DateTime64(6),
    type                String,
    col1            String,
    col2             String,
    text                String,
    col3              UInt8,
    col4            String,
    col5 String,
    col6 UInt8,
    col7 Nested (name String, version UInt16),
    col8 Nested (name String, version UInt16),
    col9 Array(String),
    col10 String,
    col11 Int32,
    col 12 UInt8,
    col13 Int16,
    col14 Int16,
    col15 Int32,
    col16 UInt8,
    col17 Decimal(10, 2),
    INDEX idx_type type TYPE set(30) GRANULARITY 4,
    INDEX idx_text lower(text) TYPE ngrambf_v1(3, 256, 2, 0) GRANULARITY 4,
    INDEX idx_time timestamp TYPE minmax GRANULARITY 4
)
    ENGINE = MergeTree() PARTITION BY toYYYYMM(timestamp) ORDER BY (col1, col2, timestamp);
```

and the query ```select name, type from system.columns where database='default' and table='events'``` shows the same thing except that instead of 

```
col7 Nested (name String, version UInt16),
col8 Nested (name String, version UInt16)
```

There is:
```
col7.name         │ Array(String)  │
│ col7.version      │ Array(UInt16)  │
│ col8.name    │ Array(String)  │
│ col8.version │ Array(UInt16)
```

I saw in an earlier issue that nested types seemed to be working, so I'm not sure where the issue could be.

**Comment by ildus** [comment]
No, they should not be supported.

**Comment by ctlaltdefeat** [comment]
That wouldn't work, as each event contains multiple instances of the nested types (which is the point of the nested type, as far as I understand).
Is it possible to define a partial foreign schema that somehow ignores the nested types? If so, how would I go about doing that?
Thanks for the quick responses!

**Comment by ildus** [comment]
Right, nested types could not be replaced by tuples.
I think I will implement ignoring nested types with some notice message, but not earlier than next monday. So you can wait until then, of would have to create tables manually.

**Comment by ildus** [comment]
@ctlaltdefeat problem was with `DateTime64`, added mapping to `timestamp`.
