### ISSUE TITLE
error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

### ISSUE THREAD

**Issue by LingangJiang** [adjust/clickhouse_fdw#35]
[  4%] Built target lz4-lib
[  6%] Built target clickhouse_fdw_sql
[  9%] Built target cityhash-lib
[ 45%] Built target clickhouse-cpp-lib-static
[ 46%] Building CXX object src/CMakeFiles/clickhouse_fdw.dir/binary.cc.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/input.h:4,
                 from /xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/coded.h:3,
                 from /xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/column.h:3,
                 from /xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/nullable.h:3,
                 from /xxx/clickhouse_fdw/src/binary.cc:6:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/coded.h:3:0,
                 from /xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/column.h:3,
                 from /xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/nullable.h:3,
                 from /xxx/clickhouse_fdw/src/binary.cc:6:
/xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/input.h:11:26: error: expected ‘;’ at end of member declaration
     virtual ~InputStream() noexcept (false)
                          ^
/xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/input.h:11:38: error: expected identifier before ‘false’
     virtual ~InputStream() noexcept (false)
                                      ^
/xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/input.h:11:38: error: expected ‘,’ or ‘...’ before ‘false’
/xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/input.h:11:43: error: ISO C++ forbids declaration of ‘noexcept’ with no type [-fpermissive]
     virtual ~InputStream() noexcept (false)
                                           ^
/xxx/clickhouse_fdw/src/clickhouse-cpp/clickhouse/columns/../base/input.h:15:26: error: ‘uint8_t’ has not been declared
     inline bool ReadByte(uint8_t* byte) {

**Comment by ildus** [comment]
`clickhouse-cpp` which is included in `clickhouse_fdw` requires `c++17`.

**Comment by LingangJiang** [comment]
> `clickhouse-cpp` which is included in `clickhouse_fdw` requires `c++17`. I suppose you're using old gcc, or maybe something wrong with your build environment.

yes, I upgrade gcc and g++ to 7, done!
