### ISSUE TITLE
support `COUNT(DISTINCT col1) FILTER (WHERE col2='xx')`

### ISSUE THREAD

**Issue by zzn01** [adjust/clickhouse_fdw#38]
`COUNT(col1) FILTER (WHERE col2='xx')` will translate to `countIf(col1, (col2='xx'))`

but with `DISTINCT`, it will try fetch much more data from clickhouse. 
it seems that:
` COUNT(DISTINCT col1) FILTER (WHERE col2='xx')` can translate to `uniqExactIf(col1, col2='xx')`

**Comment by ildus** [comment]
`uniq_exact` function is merged
