### ISSUE TITLE
Clickhouse database in IMPORT FOREIGN SCHEMA

### ISSUE THREAD

**Issue by ivan-tkatchev** [adjust/clickhouse_fdw#40]
Hi.

Do I understand correctly that when doing `IMPORT FOREIGN SCHEMA "x" FROM SERVER clickhouse INTO ch` the `"x"` is ignored?

And that if I want to import from a specific Clickhouse database (equivalent, more or less, to a Postgres schema), then I need to `CREATE SERVER` for each Clickhouse database?

Seems like an unintuitive and poor usability workflow, is there any chance this could be changed?

Thanks.

**Comment by ildus** [comment]
Hi, just pushed, in the latest commit the "x" part will mean a database name to import.
