### ISSUE TITLE
Problem with cursors

### ISSUE THREAD

**Issue by davidpsv17** [adjust/clickhouse_fdw#42]
Hi,

I'm using Tableau connected to PostgreSQL server, when I try to apply some filters it use cursors:

```
BEGIN;declare "SQL_CUR000001DB5D2F8590" cursor with hold for SELECT CAST("table1"."p1" AS TEXT) AS "p1"
        FROM "public"."table1" "table1"
        GROUP BY 1
        ORDER BY 1 ASC NULLS FIRST;fetch 2048 in "SQL_CUR000001DB5D2F8590"
```
 
When I check the query in clickhouse I see that not the full sentence has been sent:
`SELECT p1 FROM "default".table1 GROUP BY p1`

It would be possible to push down to clickhouse the entire request?

Thanks!

**Comment by ildus** [comment]
Should be fixed already.
