### ISSUE TITLE
ERROR:  clickhouse_fdw: could not append data to column - std::bad_alloc

### ISSUE THREAD

**Issue by MapleOfLeaf** [adjust/clickhouse_fdw#43]
When I create Postgres to point to a table from Clickhouse using Postgres_fdw, I used sql "insert into Postgres_clickhouse_fdw select * from Postgres_table". When I insert a clickhouse from Postgres via FDW, The following error is reported when I make more than two connections
Binary mode is used.The current server still has the remaining memory space.
ERROR:  clickhouse_fdw: could not append data to column - std::bad_alloc。

**Comment by MapleOfLeaf** [comment]
current table data count  20000000.

**Comment by ildus** [comment]
I would need some script from you to reproduce  the issue.

**Comment by MapleOfLeaf** [comment]
You can try the following:
1. Create the Clickhouse table
2. Create the Postgres external table
3. To insert data into the external table in Postgres, the amount of data required reaches 50000000.And open several more Windows to perform the insert simultaneously.
By doing so, problems arise.  
Thank you very much for your reply

**Comment by ildus** [comment]
I think it's better to split the data to chunks first, now you're basically trying to put all your data through one huge request.
