### ISSUE TITLE
crash if there are DateTime columns

### ISSUE THREAD

**Issue by avzhurav** [adjust/clickhouse_fdw#48]
Any tables in ClickHouse with data such as DateTime(time-zone) or DateTime64, e.g., DateTime('Europe/Moscow') or DateTime64(3,'UTC') follows to the crash when "IMPORT FOREIGN SCHEMA" in PostgreSQL (version 12.4):

server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

The current workaround is a view in ClickHouse with conversion to timestamp.

But probably it can be nice to add some reasonable exception message if some "unknown or bad" types are present.

**Comment by ildus** [comment]
I have DateTime fields in tests for IMPORT and they're not failing. I would need the scheme you're trying to import, and steps to reproduce.

**Comment by avzhurav** [comment]
Environment:
1) CentOS Linux release 7.8.2003 (Core) - on all machines
2) ClickHouse client version 20.9.2.20 (official build). Connecting to localhost:9000 as user default. Connected to ClickHouse server version 20.9.2 revision 54439.
3) psql (9.2.24, server 12.4) WARNING: psql version 9.2, server version 12.0.

ClickHouse part -------------------------------

create database dummy;

create table dummy.test_crash(recordedTime DateTime64(3,'UTC'),receivedTime  DateTime('Europe/Moscow')) ENGINE = MergeTree PARTITION BY toYYYYMM(recordedTime) ORDER BY (receivedTime) SETTINGS index_granularity=8192;

insert into dummy.test_crash values(now(),now());

select * from dummy.test_crash;
---- result -----------------------
┌────────────recordedTime─┬────────receivedTime─┐
│ 2020-10-03 21:03:28.000 │ 2020-10-04 00:03:28 │
└─────────────────────────┴─────────────────────┘

PostgreSQL part -------------------------------

CREATE EXTENSION clickhouse_fdw;

CREATE SERVER clickhouse_svr2 FOREIGN DATA WRAPPER clickhouse_fdw OPTIONS(dbname 'dummy',host 'clickhouse-1', driver 'binary');

CREATE USER MAPPING FOR CURRENT_USER SERVER clickhouse_svr2 OPTIONS (user 'default', password '');

CREATE SCHEMA click2;

IMPORT FOREIGN SCHEMA "dummy" FROM SERVER clickhouse_svr INTO click2;

... ups ....

postgres=# IMPORT FOREIGN SCHEMA "dummy" FROM SERVER clickhouse_svr INTO click2;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>

**Comment by ildus** [comment]
@avzhurav pushed the bugfix, could you test on your side?

**Comment by avzhurav** [comment]
Hi @ildus , sorry for delay, that was a great job! Thank you a lot! Everything works fine now, except the only one: ClickHouse DateTime64 is a read-only from Postgres now, I can read it in Postgres, but cannot write it back: "psql>insert into sss values(now());" -> "unexpected column type for TIMESTAMPOID: DateTime64(6)". 
Probably it's just because there is no backward conversion from Postgres's timestamp to ClickHouse DateTime64 in "column_append" function in "src/binary.cc" , but it can be a challenge for implementation, because ClickHouse DateTime64 has a precision settings, e.g., it can be DateTime64(1) or DateTime64(3) or DateTime64(XX).
In any case, thank you a lot!
