### ISSUE TITLE
ClickHouse DateTime64 is a read-only in Postgres

### ISSUE THREAD

**Issue by avzhurav** [adjust/clickhouse_fdw#49]
ClickHouse DateTime64 is a read-only in Postgres, I can read it in Postgres, but cannot write it back: 
"psql>insert into sss values(now());" -> "unexpected column type for TIMESTAMPOID: DateTime64(6)". 
Probably it's just because there is no backward conversion from Postgres's timestamp to ClickHouse DateTime64 in "column_append" function in "src/binary.cc" , but it can be a challenge for implementation, because ClickHouse DateTime64 has a precision settings, e.g., it can be DateTime64(1) or DateTime64(3) or DateTime64(XX).
Thanks.

**Comment by ildus** [comment]
Should work now.

**Comment by avzhurav** [comment]
Everything is fine now!
But maybe it would be helpful to add a small note about using UTC in the README file?
Simply because if the time zone is not specified in the column definition, ClickHouse uses the value of the time zone parameter in the server settings or in the operating system settings at the time the ClickHouse server was started. And this may come as a surprise.
In any case, everything works, thank you!
