### ISSUE TITLE
Clickhouse database in IMPORT FOREIGN SCHEMA

### ISSUE THREAD

**Issue by ivan-tkatchev** [adjust/clickhouse_fdw#50]
#40 is closed as fixed, but it doesn't really work as intended:

```
CREATE SERVER clickhouse_my_stuff FOREIGN DATA WRAPPER clickhouse_fdw OPTIONS(host '10.2.3.4', port '8123');    -- OK
CREATE USER MAPPING FOR CURRENT_USER SERVER clickhouse_my_stuff OPTIONS (user 'readonly', password 'qwerty');    -- OK
CREATE SCHEMA my_stuff;    -- OK
IMPORT FOREIGN SCHEMA "some_db" FROM SERVER clickhouse_my_stuff INTO my_stuff;    -- OK

SELECT * FROM my_stuff.some_table;    -- ERROR:
ERROR:  clickhouse_fdw:Code: 60, e.displayText() = DB::Exception: Table default.some_table doesn't exist.
QUERY:SELECT a, b, c FROM "default".some_table
```

**Comment by ildus** [comment]
Even if you import some other database, the queries will use database specified in settings of  foreign server (from CREATE SERVER, default value is `default`).

**Comment by ivan-tkatchev** [comment]
I understand. The question is - is it possible to fix this? Having to create a separate foreign server for every database seems wrong.

**Comment by ildus** [comment]
Pushed the fix, now IMPORT will create `database` option in foreign tables. You can use it to fix your issue.
