### ISSUE TITLE
Unknown function btrim

### ISSUE THREAD

**Issue by fantom0005** [adjust/clickhouse_fdw#51]
Hi guys.

I tried to use function trim in "where" block in postgres and got the error message: "Unknown function btrim QUERY:SELECT field FROM "default".test_table WHERE ((btrim(field) <> ''))"

How to reproduce: 
1. Create table in ClickHouse 
```SQL
create table test_table (field String) engine = MergeTree() ORDER BY (field);
```
2. Add value to table 
```SQL
insert into test_table values ('213');
```
3. Create fdw table in postgres
```SQL
create foreign table test_table ("field" text) server clickhouse_svr;
```
4. Select data and use function trim in where 
```SQL
select * from test_table where trim(field) <> '';
```

I checked on versions:
- PostgreSQL 12.3 (Debian 12.3-1.pgdg110+1+b1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 9.3.0-14) 9.3.0, 64-bit
- ClickHouse Verion 20.5.4.40

**Comment by fantom0005** [comment]
I found workaround. But it's very strange

You can use functions **ltrim**, **rtrim**  together. It works.

```SQL
select * from test_table where ltrim(rtrim(field)) <> '';
```

**Comment by ildus** [comment]
It's not strange, clickhouse already has `ltrim` and `rtrim` functions, but not `btrim`. I haved added translation to `trimBoth`.
