### ISSUE TITLE
Could not find PG_REGRESS

### ISSUE THREAD

**Issue by vlauzeckas** [adjust/clickhouse_fdw#53]
hi, I am trying to compile sources based on instructions, but getting such errors. any tips on how to solve it would be really helpful. could  not find how to install this pg_regress 

```
user@postgresbi:~/clickhouse_fdw/build$ cmake ..
-- Setting clickhouse_fdw build type -
CMake Error at CMakeLists.txt:51 (find_program):
  Could not find PG_REGRESS using the following names: pg_regress


-- Configuring incomplete, errors occurred!
See also "/home/user/clickhouse_fdw/build/CMakeFiles/CMakeOutput.log".

```

**Comment by ildus** [comment]
`pg_regress` usually comes with postgresql package. It depends on your linux distrubution.

**Comment by vlauzeckas** [comment]
user@postgresbi:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

PostgreSQL 10.4 (Ubuntu 10.4-2.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit

Can i install it somehow? I tried to find it, but could not find anything usefull.

**Comment by ildus** [comment]
@vlauzeckas as I remember there should be -dev package for postgres in ubuntu, but I don't remember exact name.

**Comment by vlauzeckas** [comment]
thanks ildus, you pointed me on the right direction. i installed postgresql-server-dev-XX and it went through. 
i really appriciate that. owe you beer 👍
