### ISSUE TITLE
Crash when table has LowCardinality(Nullable(String)) field

### ISSUE THREAD

**Issue by mzealey** [adjust/clickhouse_fdw#55]
Pg 12.5, latest clickhouse-fdw, latest clickhouse:20 docker image.

In clickhouse:

```
CREATE TABLE test (
    time DateTime ,
    test LowCardinality(Nullable(String))
) ENGINE = MergeTree()
PARTITION BY toDate(time)
ORDER BY (time);         
```

`IMPORT FOREIGN SCHEMA "test" FROM SERVER clickhouse_svr INTO public;` then crashes.

`LowCardinality(String)` and `Nullable(String)` work fine by themselves.

**Comment by ildus** [comment]
Hi, binary or http protocol?

**Comment by mzealey** [comment]
both i think

**Comment by ildus** [comment]
IMPORT should be fixed, along with queries on `http` protocol. But `LowCardinality(Nullable)` columns would not work on `binary` protocol, since library I use for the communication doesn't support them.

**Comment by mzealey** [comment]
confirm this works thanks
