### ISSUE TITLE
crash on IPv4 / IPv6 types on import foreign schema

### ISSUE THREAD

**Issue by mzealey** [adjust/clickhouse_fdw#56]
```
create table t (t IPv4) engine=MergeTree() order by tuple();
```

```
IMPORT FOREIGN SCHEMA "default" LIMIT TO (t) FROM SERVER clickhouse_svr INTO public;
```

crashes. I guess the same with IPv6 data type. Using http driver.

**Comment by mzealey** [comment]
(is it not possible to print a nice error message if unknown type is detected?)

**Comment by ildus** [comment]
It's a poor designed parser, I will look into it, thanks.
