### ISSUE TITLE
Error when working with uppercase letters

### ISSUE THREAD

**Issue by ELDIABLO4400** [adjust/clickhouse_fdw#6]
Example:
#Clickhouse version
create table Messages
(
    LineTopic String,
    weight Float64,
    `length` Float64,
    task_speed Float64,
    density Float64,
    ts datetime
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(ts)
ORDER BY (LineTopic , ts)

#Postgres version
CREATE FOREIGN TABLE Messages(
	LineTopic text,
	weight numeric(10, 2),
	length numeric(10, 2),
	task_speed numeric(10, 2),
	density numeric(10, 2),
	ts timestamp(0)
) SERVER clickhouse_svr OPTIONS (table_name 'Messages');

Select * from Messages Limit 5;
Result:
ERROR:  clickhouse_fdw:Code: 47, e.displayText() = DB::Exception: Missing columns: 'linetopic' while processing query: 'SELECT linetopic, weight, length, task_speed, density, ts FROM mlines.Messages ', required columns: 'weight' 'linetopic' 'density' 'length' 'task_speed' 'ts', source columns: 'density' 'ts' 'task_speed' 'length' 'LineTopic' 'weight'
QUERY:SELECT linetopic, weight, length, task_speed, density, ts FROM mlines."Messages"

When I replaced **LineTopic** on **line_topic**, it's working.
Should it be so?

**Comment by ildus** [comment]
Yes, that's `postgres` behavior. You should create table like this:
```
CREATE FOREIGN TABLE Messages(
"LineTopic" text,
weight numeric(10, 2),
length numeric(10, 2),
task_speed numeric(10, 2),
density numeric(10, 2),
ts timestamp(0)
) SERVER clickhouse_svr OPTIONS (table_name 'Messages');
```

**Comment by ELDIABLO4400** [comment]
Ok, Thank's.
