### ISSUE TITLE
utf-8 strings are show in wrong encoding inside PG

### ISSUE THREAD

**Issue by akrisanov777** [adjust/clickhouse_fdw#64]
I'm using PostgreSQL 13.1 and CH 20.9.3.45.
String values containing UTF-8 symbols are showed improperly:
![image](https://user-images.githubusercontent.com/39487712/106044534-e8dac100-60f0-11eb-9cf2-419c560fcae2.png)

Is it a bug or should I specify encoding somehow?

**Comment by akrisanov777** [comment]
Succede to fix the issue in Python by encoding form iso_8859_1 to utf 8:

s.encode('iso_8859_1').decode()

**Comment by ildus** [comment]
Can't reproduce, please check make sure you use UTF-8 in both of your databases.
