### ISSUE TITLE
Symbols mutation in string when reading from Postgres via Clickhouse FDW

### ISSUE THREAD

**Issue by fantom0005** [adjust/clickhouse_fdw#68]
I have found bug with strings in clickhouse FDW. If you have string with square brackets in clickhouse and you select this string in postgres via clickhouse fdw then you'l see curly braces.

For example,
This clickhouse table with string
```
d          |   test_column
----------------
2020-01-01 |   [asd]
``` 

This fdw table select  in Postgres
```
d          |   test_column
----------------
2020-01-01 |   {asd}
``` 

How to reproduce:
1. Create table in ClickHouse
```sql
CREATE TABLE test_table (
    d DateTime,
    test_column String
) ENGINE MergeTree()
PARTITION BY toYYYYMM(d)
ORDER BY d;
```

2. Add value to clickhouse table
```sql
INSERT INTO test_table (*) VALUES ('2020-01-01', '[asd]');
```

3. Create fdw table in postgres
```sql
CREATE FOREIGN TABLE IF NOT EXISTS test_table(
    d Date,
    test_column Text
) SERVER clickhouse_svr;
```

4. Select data from fdw table in postgres

**Comment by ildus** [comment]
Thank you, fixed
