### ISSUE TITLE
Aggregates argMin, argMax

### ISSUE THREAD

**Issue by VernonVega** [adjust/clickhouse_fdw#7]
Is there any way to implement in FDW Clickhouse-specific aggregate functions? Those like argMin, argMax would be very useful.

**Comment by ildus** [comment]
I'm thinking about some solution to add custom mappings without making changes to fdw source code. But for now I can add functions you need to source code. Could you write exact list of functions that you need right now?

**Comment by VernonVega** [comment]
Adding some smart mapping that would work for any existing functions would be nice! You're doing a great job! At this moment argMin and argMax we need most of all, thank you.

**Comment by ildus** [comment]
I have added limited support of argMin and argMax in latest master, they should work when second argument `int`.

**Comment by VernonVega** [comment]
Is it possible to use DateTime as a second argument? The idea is to query something when the date field is latest or earliest.

**Comment by ildus** [comment]
you would need timestamp without or with time zone?

**Comment by petshop** [comment]
without tz at this moment

**Comment by VernonVega** [comment]
without tz at this moment

**Comment by ildus** [comment]
I've added some support, hope it will help.

**Comment by VernonVega** [comment]
When I try to make a build I get an error which I haven't got before:

` Building C object src/CMakeFiles/clickhouse_fdw.dir/clickhousedb_fdw.c.o
In file included from /usr/include/postgresql/11/server/nodes/pg_list.h:40:0,
                 from /usr/include/postgresql/11/server/access/tupdesc.h:19,
                 from /usr/include/postgresql/11/server/access/htup_details.h:18,
                 from /media/extended/SymLink/Downloads/clickhouse_fdw-master/src/clickhousedb_fdw.c:17:
/media/extended/SymLink/Downloads/clickhouse_fdw-master/src/clickhousedb_fdw.c: In function ‘clickhouseBeginForeignInsert’:
/usr/include/postgresql/11/server/nodes/nodes.h:628:27: warning: implicit declaration of function ‘typeof’ [-Wimplicit-function-declaration]
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                           ^
/media/extended/SymLink/Downloads/clickhouse_fdw-master/src/clickhousedb_fdw.c:1319:9: note: in expansion of macro ‘copyObject’
   rte = copyObject(rte);
         ^
/usr/include/postgresql/11/server/nodes/nodes.h:628:40: error: expected ‘)’ before ‘copyObjectImpl’
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
`
I can't say for sure if it's because of a different build environment (but I tried on centos7 and ubuntu 16.04) or it is somehow connected to changes in your code. Have you got any ideas? Thanks in advance.

**Comment by ildus** [comment]
I can say for sure that's related with changes. I think same problem will happen you'll try to compile postgres on these machines.

**Comment by ildus** [comment]
pushed possible fix to latest master

**Comment by VernonVega** [comment]
Man, you did it! Thanks, now it works like a charm!
