### ISSUE TITLE
how to send "FINAL" to clickhouse in query to replacingmergetree?

### ISSUE THREAD

**Issue by kolykhalov** [adjust/clickhouse_fdw#70]
I expect the query "select * from my_materialized_view final" with replacingmergetree engine to return merged data, but it doesn't. Looks like PGsql treats "FINAL" as an alias to "my_materialized_view" and ignores it. 

Thanks for any suggestions on this.

**Comment by ildus** [comment]
Hi, you can't use clickhouse syntax on the postgres side.

**Comment by kolykhalov** [comment]
Hello @ildus ! I know that, but FINAL is required for replacingmergetree otherwise it may not replace at the time of query which is required. How to solve it?

**Comment by ildus** [comment]
You should never use the `final` keyword in your queries, especially when it comes to production environment or large tables, in case of ReplacingMergeTree you should look into `argMax` function
