### ISSUE TITLE
Functions that do not support in where clause

### ISSUE THREAD

**Issue by wucheong** [adjust/clickhouse_fdw#72]
Hello guys!

Recently I am working some SQL script which using PostgreSQL function "strpos".
It do works in select part of SQL.
`SELECT
id,
name,
strpos(name, 'John')
FROM dummy_table`

However, when I try to use it in a where clause, it will directly pass "strpos" function to Clickhouse which clickhouse did not support. In clickhouse, there some function with different name "**position**" which only name difference.

`SELECT
id,
name,
FROM dummy_table
WHERE strpos(name, 'John')>0`

`DB::Exception: Unknown function strpos: `

I know there is a work around which using "LIKE" in where clause. But due to some integration reason, I would like try to work on this.

May I ask if below is the part I need to work with?

https://github.com/adjust/clickhouse_fdw/blob/fd1f3ec585b73ed61afcd3334db535e79969fb83/src/adjust.c#L116-L149

**Comment by wucheong** [comment]
After some of research, the function should be `F_TEXTPOS`

**Comment by ildus** [comment]
Hi, can you make the PR with this change?

**Comment by ildus** [comment]
Added

**Comment by wucheong** [comment]
> Added

Thanks for feature added.
Faster than me starting to work with. :)
