### ISSUE TITLE
Support limit pushdown

### ISSUE THREAD

**Issue by mkabilov** [adjust/clickhouse_fdw#8]
In some cases after grouping by certain column(s) ClickHouse still might return a lot of rows, so performing LIMIT on clickhouse side will be beneficial.

**Comment by alanrigele** [comment]
The limit pushed down is not working. 

Any plans to address this

**Comment by ildus** [comment]
No, for now I'm not planning to implement this

**Comment by angryhans** [comment]
I also want this feature very much.
We are using some BI tools,
It crashes when loading a lot of data to preview,
because the LIMT condition was not pushed down to Clickhouse.

@ildus Would you please solve this problem?

**Comment by reignmaker** [comment]
Hello!

First of all, let me thank you for your incredible work! (I was literaly amazed wen I saw how the complex `aggr(column) filter(where)` is mapped into CH's syntax! Pure magick!)
Unfortunately, the `LIMIT` pushdown is holding us to completely switching (that would be a drop in replacement!) to CH.
Could you please, at least, share with all of us your current plan about implementing the `LIMIT` pushdown?
Thank you!

**Comment by ildus** [comment]
@reignmaker just pushed, could check on your data?

**Comment by davidpsv17** [comment]
Hi @ildus !

how can I enable it? I'm not able to push down the limit.

Thanks!

**Comment by ildus** [comment]
@davidpsv17 forgot to mention, it is supported only on pg12 and higher, since it was introduced there.

**Comment by reignmaker** [comment]
@ildus Thank you very much! It works great!

**Comment by davidpsv17** [comment]
sorry @ildus! I was using pg11, with pg12 works fine!
